### ISSUE TITLE
[1.16.1] Backpacks can be placed in backpacks causing NBT tag overflow

### ISSUE THREAD

**Issue by Vaerys-Dawn** [MC-U-Team/Usefull-Backpacks-1.10.x#45]
**Describe the bug**
Putting a backpack inside a backpack can create a max NBT tag size error

**To Reproduce**
1. get a backpack
2. put a backpack in a backpack (preferably with other items in it)
3. repeat until crash

**Expected behavior**
You should not be able to put backpacks inside of backpacks (see: shulker boxes)

**Versions**
- Mod version: Useful-Backpacks-1.16.1-1.11.2.74
- Minecraft version: 1.16.1
- Forge version: forge-32.0.108
- UTeamCore version: 3.1.3.170

**Comment by HyCraftHD** [comment]
Please use the server config option to disable nbt sharing to the client:
The config option is shareAllNBTData in your "world name"/serverconfig/usefulbackpacks-server.toml

This will fix this issue, but will make it unusable in creative mode.

The fix that you cannot stack backpacks in backpacks is just not working, when using modded items, because any other item can have that much nbt to cause this issue :/

For a deeper analysis here is the original issue: #24

**Comment by Vaerys-Dawn** [comment]
*sigh* I reported this because allowing you to put a backpack in a backpack is no doubt going to cause issues, vanilla outright refuses to let shulkerboxes go in one another because It can potentially cause major issues, for example an NBT tag overflow. Is this a won't fix because you couldn't figure out how to blacklist your item from being able to put it in it'self or something else.

**Comment by HyCraftHD** [comment]
I doubt you have read anything a posted above and in #24 .

Yes it is a possibility to prevent backpacks in backpacks. However it does not fix any root issue about the nbt overflow.
Yes you can trigger the overflow way easier with backpacks in backpacks, but only when you really try to do that.

Most of the time its very useful to stack backpacks in backpacks and will not cause issues unless stacking items with large nbt tags in backpacks in backpacks.

I'm open for a config option if you wanna pr it cuz don't I have time to do that right now.
