### ISSUE TITLE
Crash after launching game 

### ISSUE THREAD

**Issue by UnFulano29** [MC-U-Team/Usefull-Backpacks-1.10.x#58]
Describe the bug: So everytime I launch Minecraft it never gets to the mainscreen but shows a crash message. I have reinstalled the mod several times and I'm using the latest version. Message says: "Encountered an error during the load_registries even phase"
I must add I'm trying to play with another 27 mods, none of them are showing me an error message ;-;

Expected behavior: Launch and play the game as usual

Versions

Mod version: 1.11.6.87
Minecraft version: 1.16.4
Forge version: 35.1.37
UTeamCore version: 3.1.17.192

Log (if crash occures) 
[crash-2021-02-08_00.37.20-fml.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5941470/crash-2021-02-08_00.37.20-fml.txt)

I hope you help me and thank you so much.

**Comment by firestorm2039** [comment]
i had similar issue and i had not updated forge to 35.1.37, since i updated it, it now works fine. (my post is below yours)
i am no expert in any of this sorry, but i would suggest trying to install forge 35.1.37 again, i dont know if it would be a mod that does not work with it, as i usually get another error messaging telling me why on screen .

EDIT: i have also heard that not giving minecraft enough RAM causes crashes, looks like you have loads of mods installed which could be a reason as well i think? have you tried giving forge more ram to use? if you have a 16GB ram i suggest changing minecraft to 8GB (my PC is 8GB ram and i have minecraft at 6GB, which is a bit iffy as using more than half can cause problems i have been told).
anyway to change this launch minecraft (stay on screen where you can select forge or minecraft launcher, see picture below), then click on installations, find your forge version and click the 3 lines and click edit, select more options and under Jvm Arguments you will see a few letters and a number follow by the letter G (see picture below), change this NUMBER to the amount of RAM you want it to use and click save, i believe its usually set at 2G, but like i said i changed mine to 6G.

i have no idea if this will help or not?, but no harm in trying i suppose, i know changing mine stopped my game from freezing during gameplay.
![Untitled](https://user-images.githubusercontent.com/75093996/107423710-93e97280-6b14-11eb-8cfb-13ff6a3e2ba3.png)
![Untitled 1](https://user-images.githubusercontent.com/75093996/107423720-98159000-6b14-11eb-8762-e0daa3c7ed00.png)

**Comment by HyCraftHD** [comment]
Actually the problem lies that @UnFulano29 is using the -dev version which will not work outside of development workspaces
Please use the normal version
