### ISSUE TITLE
Won't upgrade to Medium

### ISSUE THREAD

**Issue by AmaranthineDream** [MC-U-Team/Usefull-Backpacks-1.10.x#6]
have no idea if there's a problem going from medium to large, but when I put all the ingredients needed for the medium size on the crafting table, nothing shows up - I've tried re-downloading the mod as well as exiting Minecraft and rebooting, i'm not sure what else to do.

**Comment by HyCraftHD** [comment]
Oh, my fault. You are using 1.13.2 right?
The crafting recipes have changed and i forgot to update them.
You now need instead of the upper middle backpack a leather to upgrade from small to medium and from medium to large.

![grafik](https://user-images.githubusercontent.com/7681220/53088753-f5207180-350a-11e9-924b-f61406c6741b.png)

**Comment by AmaranthineDream** [comment]
Thank you very much - tested and working
